In [1]:
import cv2
import numpy as np

zero_mat=np.zeros((360,640),np.uint8)

#defining the region of interest
vertices=np.array([[640,360],[640,270],[420,150],[390,150],[0,280],[0,360]])
vertices1=np.array([[640,360],[640,260],[380,260],[380,360]])

#vertices1=np.array([[640,100],[420,160],[0,420]])
cv2.fillPoly(zero_mat,[vertices],(255))
#to cut out the car
cv2.fillPoly(zero_mat,[vertices1],(0))

cv2.imshow("zer",zero_mat)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [2]:
cap=cv2.VideoCapture("lane_detect.mp4")

while(cap.isOpened()):
    ret, frame=cap.read()
    if not ret:
        break
    #print(frame.shape)

    re_frame=cv2.pyrDown(frame)
    gr_frame=cv2.cvtColor(re_frame,cv2.COLOR_BGR2GRAY)
    #mask_frame1=cv2.bitwise_and(gr_frame,zero_mat)

    gr_frame=cv2.blur(gr_frame,(4,4))
    edg_frame=cv2.Canny(gr_frame,50,150)
    mask_frame=cv2.bitwise_and(edg_frame,zero_mat)

    
    contours, hierarchy =cv2.findContours(mask_frame,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
    #contours, hierarchy =cv2.findContours(mask_frame,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
    
    for c in contours:
        area = cv2.contourArea(c)
        if area>5:
            cv2.drawContours(re_frame,[c],0,(255,0,255),2)
            M=cv2.moments(c)
            if M["m00"]!=0:
                cx=int(M["m10"]/M["m00"])
                cy=int(M["m01"]/M["m00"])
                cv2.circle(re_frame,(cx,cy),2,(0,0,255),3)
    for h in hierarchy:
        print(h)
                
    lines = cv2.HoughLinesP(mask_frame,2,np.pi/180,100,minLineLength=100,maxLineGap=10)
    
    if lines is not None:
        for line in lines:
            x1,y1,x2,y2=line[0]
            cv2.line(re_frame,(x1,y1),(x2,y2),(0,255,0),2)       
            
    #CV2.line(re_frame,)
    cv2.imshow("frame",re_frame)
    #cv2.imshow("frame",mask_frame1)
    
    
    if cv2.waitKey(100) & 0xFF==ord("q"):
        break
cap.release()
cv2.destroyAllWindows()

[[ 1 -1 -1 -1]
 [ 2  0 -1 -1]
 [ 3  1 -1 -1]
 [ 4  2 -1 -1]
 [ 5  3 -1 -1]
 [ 6  4 -1 -1]
 [ 7  5 -1 -1]
 [ 8  6 -1 -1]
 [ 9  7 -1 -1]
 [10  8 -1 -1]
 [12  9 11 -1]
 [-1 -1 -1 10]
 [13 10 -1 -1]
 [14 12 -1 -1]
 [15 13 -1 -1]
 [16 14 -1 -1]
 [17 15 -1 -1]
 [18 16 -1 -1]
 [19 17 -1 -1]
 [20 18 -1 -1]
 [21 19 -1 -1]
 [22 20 -1 -1]
 [23 21 -1 -1]
 [24 22 -1 -1]
 [-1 23 -1 -1]]
[[ 1 -1 -1 -1]
 [ 2  0 -1 -1]
 [ 3  1 -1 -1]
 [ 4  2 -1 -1]
 [ 5  3 -1 -1]
 [ 6  4 -1 -1]
 [ 7  5 -1 -1]
 [ 8  6 -1 -1]
 [ 9  7 -1 -1]
 [10  8 -1 -1]
 [12  9 11 -1]
 [-1 -1 -1 10]
 [13 10 -1 -1]
 [14 12 -1 -1]
 [15 13 -1 -1]
 [16 14 -1 -1]
 [17 15 -1 -1]
 [18 16 -1 -1]
 [19 17 -1 -1]
 [20 18 -1 -1]
 [21 19 -1 -1]
 [22 20 -1 -1]
 [23 21 -1 -1]
 [24 22 -1 -1]
 [-1 23 -1 -1]]
[[ 1 -1 -1 -1]
 [ 2  0 -1 -1]
 [ 3  1 -1 -1]
 [ 4  2 -1 -1]
 [ 5  3 -1 -1]
 [ 6  4 -1 -1]
 [ 7  5 -1 -1]
 [ 8  6 -1 -1]
 [ 9  7 -1 -1]
 [10  8 -1 -1]
 [11  9 -1 -1]
 [12 10 -1 -1]
 [13 11 -1 -1]
 [14 12 -1 -1]
 [15 13 -1 -1]
 [16 14 -1 -1]
 [17 15 